let name="Ankit Kumar";
let school="DAV";
let grade=6;
let section="D";
let rollno=12;
let marks1=84;
let marks2=90;
let marks3=96;
var marks=(marks1+marks2+marks3)/3
console.log(name,school,grade,section,rollno,marks, end=" ")